### ISSUE TITLE
Program

### ISSUE THREAD

**Issue by mig4ng** [NeoScript/LeagueChatClient#1]
Hi,
I'm very interested in your client, I have some questions, what program are you configuring it in, and is it already finished or in some working stage I could test?

**Comment by NeoScript** [comment]
I'm not quite sure what you mean by "what program are you configuring it in" but here are some details that might help answer that question:
1) This is written 100% in Java 8.0 using JavaFX for the GUI design.
2) The .fxml files are templates which hold the information for the FXMLLoader class to read in and create the displayed window.
3) I am using a pre-written library to connect to the servers (https://github.com/TheHolyWaffle/League-of-Legends-XMPP-Chat-Library)

As for the working stage, you can currently download the project and compile it yourself (the ChatClient is the starting class). I will be adding more features as I get time, but as for now it is  in a very simple state.

Login preview-> http://i.imgur.com/2yk02rg.png
The rest of the program will follow a similar style, and ill be uploading new pictures when i get more stuff added in.

**Comment by mig4ng** [comment]
Thx for the reply, I was searching for the JavaFX xd
I tested your client before the reply, I used netbeans to compile, I don't know if in JavaFX it has the same bug but when I run it, I have to press enter before I can fill the login and password or the login button will remain red, it looks good, keep doing the great job!

**Comment by NeoScript** [comment]
thanks buddy :smiley:
